# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: .NET Core Desktop

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

defaults:
  run:
    working-directory: src/Ks.GitHub.Nuget.Sample

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # .NET 6 ビルド準備
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install Swashbuckle.AspNetCore.Cli
        run: dotnet tool install --version 6.2.3 Swashbuckle.AspNetCore.Cli

        # Release ビルド
      - name: Build with dotnet
        run: dotnet build --configuration Release
