# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: .NET Core Desktop

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

defaults:
  run:
    working-directory: src/Ks.GitHub.Nuget.Sample/Ks.GitHub.Nuget.Sample

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # .NET 6 ビルド準備
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

        # Release ビルド
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
        # Packege Push
      - name: Pack
        dotnet pack src/Ks.GitHub.Nuget.Sample.Model/Ks.GitHub.Nuget.Sample.Model.csproj -o artifacts/
      
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts
          
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Kentem-no-okada/index.json" -n "github" -u Kentem-no-okada -p ${{secrets.Nuget.Sample}} --store-password-in-clear-text
          dotnet nuget push "*.nupkg" --api-key ${{secrets.Nuget.Sample}} --source "github" --skip-duplicate
